CREATE TABLE public."Chains" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "Type" smallint NOT NULL,
    "Value" text NOT NULL,
    "TaskId" bigint NOT NULL
);
CREATE TABLE public."CodeFormats" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Index" integer NOT NULL,
    "Name" text NOT NULL,
    "Length" integer NOT NULL,
    "ConstValue" text,
    "SchemeId" bigint NOT NULL,
    "IsPartOfSn" boolean NOT NULL DEFAULT false,
    CONSTRAINT "FK_CodeFormats_Schemes_SchemeId"
        FOREIGN KEY ("SchemeId")
        REFERENCES public."Schemes"("Id")
        ON DELETE CASCADE
);
CREATE TABLE public."Counters" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Counter" bigint NOT NULL,
    "Name" text NOT NULL,
    "Type" smallint NOT NULL,
    "CreationDate" timestamp without time zone NOT NULL
);

CREATE UNIQUE INDEX "IX_Counters_Name"
ON public."Counters" ("Name");
CREATE TABLE public."Items" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SN" varchar(128) NOT NULL,
    "Crypto" varchar(255),
    "Code" varchar(32) NOT NULL,
    "SampleType" smallint NOT NULL,
    "State" smallint NOT NULL,
    "Grade" smallint,
    "ParentId" bigint,
    "TaskId" bigint NOT NULL,
    "ItemType" smallint NOT NULL DEFAULT 0,
    "Volume" double precision,
    "Weight" double precision,
    "VerificationTime" timestamp without time zone,
    "SchemeId" bigint,

    CONSTRAINT "FK_Items_Items_ParentId"
        FOREIGN KEY ("ParentId")
        REFERENCES public."Items"("Id"),

    CONSTRAINT "FK_Items_Tasks_TaskId"
        FOREIGN KEY ("TaskId")
        REFERENCES public."Tasks"("Id")
        ON DELETE CASCADE
);

CREATE INDEX "IX_Items_ParentId" ON public."Items" ("ParentId");
CREATE INDEX "IX_Items_TaskId" ON public."Items" ("TaskId");
CREATE INDEX "IX_Items_TaskId_ItemType_ParentId"
    ON public."Items" ("TaskId", "ItemType", "ParentId");
CREATE INDEX "IX_Items_TaskId_ParentId"
    ON public."Items" ("TaskId", "ParentId");
CREATE TABLE public."LogsForItem" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Description" text NOT NULL,
    "Source" smallint NOT NULL,
    "Type" smallint NOT NULL,
    "Created" timestamp without time zone NOT NULL,
    "ItemId" bigint NOT NULL,

    CONSTRAINT "FK_LogsForItem_Items_ItemId"
        FOREIGN KEY ("ItemId")
        REFERENCES public."Items"("Id")
        ON DELETE CASCADE
);

CREATE INDEX "IX_LogsForItem_ItemId"
ON public."LogsForItem" ("ItemId");
CREATE TABLE public."Schemes" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TaskId" bigint NOT NULL,
    "ItemLength" double precision NOT NULL,
    "ItemWidth" double precision NOT NULL,
    "ItemHeight" double precision NOT NULL,
    "ColumnCount" integer NOT NULL DEFAULT 0,
    "CountInParent" integer NOT NULL DEFAULT 0,
    "LayerCount" integer NOT NULL DEFAULT 0,
    "RowsCount" integer NOT NULL DEFAULT 0,
    "IsAutoPacking" boolean NOT NULL DEFAULT false,
    "ItemType" smallint NOT NULL DEFAULT 0,
    "IsTypography" boolean NOT NULL DEFAULT false,
    "IsGeneratedOnL2" boolean NOT NULL DEFAULT false,
    "GTIN" text NOT NULL DEFAULT '',

    CONSTRAINT "FK_Schemes_Tasks_TaskId"
        FOREIGN KEY ("TaskId")
        REFERENCES public."Tasks"("Id")
        ON DELETE CASCADE
);

CREATE INDEX "IX_Schemes_TaskId"
ON public."Schemes" ("TaskId");
CREATE TABLE public."Tasks" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SN" text NOT NULL,
    "Title" text NOT NULL,
    "L3_GUID" varchar(128) NOT NULL,
    "BatchCount" integer NOT NULL,
    "Created" timestamp without time zone NOT NULL,
    "ProductionDateL3" text NOT NULL,
    "ExpirationDate" timestamp without time zone NOT NULL,
    "ProductionDate" timestamp without time zone NOT NULL,
    "DateCompletion" timestamp without time zone NOT NULL,
    "ExpirationDateL3" timestamp without time zone NOT NULL DEFAULT '-infinity',
    "State" smallint NOT NULL DEFAULT 0,
    "TaskAggregationType" smallint NOT NULL DEFAULT 0,
    "TaskSendState" smallint NOT NULL DEFAULT 0,
    "TaskType" smallint NOT NULL DEFAULT 0,
    "Metadata" text,
    "Name" varchar(1024) NOT NULL DEFAULT '',
    "OrganizationName" varchar(1024) NOT NULL DEFAULT '',
    "ProductName" varchar(1024) NOT NULL DEFAULT '',
    "IsLoaded" boolean NOT NULL DEFAULT false,
    "PartsMetadata" text DEFAULT '',
    "LineCode" text NOT NULL DEFAULT '',
    "PlatformCode" text NOT NULL DEFAULT '0',
    "TaskParameters" smallint,
    "Volume" text,
    "Weight" text,
    "TaskAction" numeric(20,0) NOT NULL DEFAULT 0
);
CREATE TABLE public."Templates" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" varchar(1024) NOT NULL,
    "Template" text NOT NULL,
    "TaskId" bigint NOT NULL,
    "ItemType" smallint NOT NULL DEFAULT 0,

    CONSTRAINT "FK_Templates_Tasks_TaskId"
        FOREIGN KEY ("TaskId")
        REFERENCES public."Tasks"("Id")
        ON DELETE CASCADE
);

CREATE INDEX "IX_Templates_TaskId"
ON public."Templates" ("TaskId");